clouds=fast

screen = [VHS] [SHADOWS] [SSR] [SWAY]
screen.VHS = VHS_ENABLED VHS_W VHS_H VHS_SAMPLES VHS_SPEED
screen.SHADOWS = SOFT_SHADOWS shadowMapResolution SHADOW_RANGE SHADOW_RADIUS
screen.SSR = THICKNESS STEP_SIZE MAX_STEPS MAX_DISTANCE
screen.SWAY = SWAY_LEAVES SWAY_GRASS SWAY_SPEED SWAY_AMOUNT SWAY_SIZE
screen.columns = 3

#define VHS_ENABLED